service: lambda-otel

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
  databaseName: "pokeshop"
  databaseUsername: "ashketchum"
  databasePassword: "squirtle123"
  databaseEndpoint:
    Fn::GetAtt: [ PokeDatabase, "Endpoint.Address" ]
#  vpcConfig:
#    cidrBlock: "10.0.0.0/16"
#    createNetworkAcl: false
#    createDbSubnet: true
#    createNatInstance: true
#    createBastionHost: true
#    zones:
#      - us-east-2a
#      - us-east-2b
#    subnetGroups:
#      - rds
#      - elasticache

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  vpc:
    securityGroupIds:
      - ${ssm:/default/security_group}
      - ${ssm:/ec2/security_group}
    subnetIds:
      - ${ssm:/default/subnet_id}
  environment:
    NODE_OPTIONS: --require lambda-wrapper
    COLLECTOR_ENDPOINT: http://${ssm:/ec2/dns_name}:4317
    DATABASE_URL:
      Fn::Join:
        - ""
        - - "postgres://"
          - ${self:custom.databaseUsername}
          - ":"
          - ${self:custom.databasePassword}
          - "@"
          - ${self:custom.databaseEndpoint}
          - "/"
          - ${self:custom.databaseName}
          - "?schema=public"


functions:
  minimal:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get


resources:
  Resources:
    PokeDatabase:
      Type: "AWS::RDS::DBInstance"
      Properties:
        DBName: ${self:custom.databaseName}
        AllocatedStorage: "5"
        PubliclyAccessible: true
        DBInstanceClass: "db.t3.micro"
        Engine: "Postgres"
        MasterUsername: ${self:custom.databaseUsername}
        MasterUserPassword: ${self:custom.databasePassword}

